AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Simple rekognition based content moderation scanner for Connect

Globals: # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-template-anatomy-globals.html
  Function:
    Timeout: 5
    MemorySize: 128
    Runtime: python3.11
Parameters:
  ConnectBucketName:
    Description: Amazon Connect attachments bucket name
    Type: String
Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
            - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
              - lambda.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSLambdaExecute
      Policies:
        - PolicyName: RekognitionModerateContentPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - rekognition:DetectModerationLabels
                Resource: '*'
        - PolicyName: S3ReadAccessPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:Get*
                  - s3:List*
                  - s3:Describe*,
                  - s3-object-lambda:Get*
                  - s3-object-lambda:List*
                Resource: !Join 
                  - ''
                  - - 'arn:aws:s3:::'
                    - !Ref ConnectBucketName
                    - /*
  ConnectAttachmentScanner:
    Type: AWS::Serverless::Function     # More info about Function Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
    Properties:
      Handler: app.lambda_handler
      CodeUri: rekognition_scanner
      Description: Connect Attachment Scanner 
      Role: 
        Fn::GetAtt:
          - LambdaRole
          - Arn
      ReservedConcurrentExecutions: 100
      Architectures:
      - arm64
      Tracing: Active
      Environment:
        Variables:
          POWERTOOLS_SERVICE_NAME: AttachmentScanner
          POWERTOOLS_METRICS_NAMESPACE: Powertools
          LOG_LEVEL: INFO
      Tags:
        LambdaPowertools: python
